### ISSUE TITLE
Use same/similar feature gate setting as default OpenShift

### ISSUE THREAD

**Issue by treytabner** [openshift/hypershift-toolkit#89]
To avoid confusion between which feature gates are enabled by default with OpenShift versus with the hypershift toolkit, can we keep them the same or similar?  For example [SCTPSupport is enabled by default](https://github.com/openshift/api/blob/release-4.3/config/v1/types_feature.go#L100-L111) using the kube-apiserver-operator, but not with [hypershift-toolkit](https://github.com/openshift/hypershift-toolkit/blob/master/assets/kube-apiserver/config.yaml#L27-L30).  Do we also need to sync the list for [kube-controller-manager](https://github.com/openshift/hypershift-toolkit/blob/master/assets/kube-controller-manager/config.yaml#L29-L33)?

**Comment by rtheis** [comment]
https://github.com/openshift/hypershift-toolkit/pull/103 now gives us the ability to set feature gates.  However, we need to extend this further since that PR is missing feature gate overrides for other Kubernetes components (e.g. scheduler, kube-proxy, and kubelet).  Sometimes features gates span multiple components and the setting needs to be consistent throughout.

**Comment by rtheis** [comment]
@KodieGlosserIBM when this is implemented, then we'll need to ensure all cloud provider are aware of the behavior change so they can undo the feature gates as needed.

**Comment by KodieGlosserIBM** [comment]
For components that do not support CRD feature flags need to add it to the arguments, here for example: https://github.com/openshift/hypershift-toolkit/blob/master/assets/kube-scheduler/kube-scheduler-deployment.yaml#L55

**Comment by KodieGlosserIBM** [comment]
PR for this has been merged and backported to 4.3.
